spring:
  application:
    name: yunzhou-boot-server
  boot:
    admin:
      discovery:
        ignored-services: consul,aliyun-*,baidu-*
  cloud:
    config:
      enabled: false
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: management.context-path=/foo,health.path=/ping
        register: false

#监控监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: /ping
      base-path: /foo
  endpoint:
    health:
      show-details: always
server:
  port: 9015